### ISSUE TITLE
Visualize an inclined surface in the robot visualizer

### ISSUE THREAD

**Issue by VenusPasandi** [ami-iit/matlab-whole-body-simulator#77]
Following #72, we want to provide the proper visualization of the motion on an inclined surface.

As I discussed with @traversaro, the idyntree visualizer can not visualise an inclined surface. But, @traversaro suggested to add a joint-less model representing the inclined surface.

cc: @Giulero @valentino-razza

**Comment by fabiodinatale** [comment]
In order to achieve the task, which will be carried out by me with the support of @VenusPasandi, I would ask about the following possible solution which part of the code should be modified.

> As I discussed with @traversaro, the idyntree visualizer can not visualise an inclined surface. But, @traversaro suggested to add a joint-less model representing the inclined surface.

Could it be possible to introduce this plane as an object of the visualizer rather than introducing it as a joint-less model?

CC @traversaro

**Comment by traversaro** [comment]
> In order to achieve the task, which will be carried out by me with the support of @VenusPasandi, I would ask about the following possible solution which part of the code should be modified.
> 
> > As I discussed with @traversaro, the idyntree visualizer can not visualise an inclined surface. But, @traversaro suggested to add a joint-less model representing the inclined surface.
> 
> Could it be possible to introduce this plane as an object of the visualizer rather than introducing it as a joint-less model?
> 
> CC @traversaro

If I recall correctly the visualizer, there is no concept of "object" that is differeny by joint-less model.
